name: build repository

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    env:
      CCACHE_DIR: /tmp/ccache
      GPGKEY: 0EF1B500
      GNUPGHOME: /tmp/gnupg

    steps:
    - uses: actions/checkout@v2

    - name: install base-devel
      run: |
        cat pacman.conf >> /etc/pacman.conf
        pacman -Syuq --needed --noconfirm base-devel ccache fd git namcap

    - name: setup makepkg
      run: |
        echo "::set-env name=MAKEFLAGS::-j$(nproc)"
        echo "::set-env name=PKGDEST::$PWD/pkgs"

        useradd -M builduser && chown -R builduser .
        echo "builduser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builduser
        sed -i -e 's/!ccache/ccache/' /etc/makepkg.conf
        cat makepkg.conf >> /etc/makepkg.conf
        sudo -Eu builduser env

    - name: setup gpg
      run: |
        sudo -Eu builduser gpg --import <<< "${{ secrets.GPG_PUBLIC_KEY }}"
        sudo -Eu builduser gpg --import <<< "${{ secrets.GPG_PRIVATE_KEY }}"

    - uses: actions/cache@v1
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ github.sha }}
        restore-keys: |
          ccache-

    - run: sudo -Eu builduser ccache -z

    - name: build packages
      env:
        BUILDDIR: /tmp/makepkg
        PACKAGER: ${{ secrets.PACKAGER }}
      run: |
        for pkg in $(fd -a -t directory); do
          PKGNAME="$(basename "$pkg")"
          cd "$PKGNAME"
          echo "==> Building $PKGNAME"
          echo "-> GPG key:"
          sudo -Eu builduser gpg --list-secret-key "$GPGKEY"
          yes | sudo -Eu builduser makepkg -crs --sign --noconfirm
        done

    - name: create repo db
      run: repo-add --sign ${{ env.PKGDEST }}/rsa.db.tar.zst ${{ env.PKGDEST }}/*.pkg.tar.zst
    
    - run: sudo -Eu builduser ccache --show-stats

    - uses: crazy-max/ghaction-github-pages@v2
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        target_branch: gh-pages
        build_dir: pkgs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
