name: build repository

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged

    env:
      PACKAGER: ${{ secrets.PACKAGER }}

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        cat pacman.conf >> /etc/pacman.conf
        pacman -Syuq --needed --noconfirm asp devtools

    - name: setup makepkg
      run: |
        echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
        echo "PKGDEST=$PWD/pkgs" >> $GITHUB_ENV

        useradd -M builduser
        echo 'builduser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builduser
        cat makepkg.conf >> /etc/makepkg.conf

    - name: generate dynamic packages
      run: |
        while read pkg; do
          curl -sSL "https://aur.archlinux.org/cgit/aur.git/snapshot/$pkg.tar.gz" | tar zxvf -
        done < aur_packages.txt

    - name: build packages
      run: find -name PKGBUILD -execdir sudo -u builduser extra-x86_64-build \;

    - name: create repo db
      run: repo-add ${{ env.PKGDEST }}/rsa.db.tar.zst ${{ env.PKGDEST }}/*.pkg.tar.zst
    
    - run: cp -LR ${{ env.PKGDEST }} output

    - uses: crazy-max/ghaction-github-pages@v2
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        target_branch: gh-pages
        build_dir: output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
