name: build repository

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-20210131.0.14634


    env:
      CCACHE_DIR: /tmp/ccache

    steps:
    - uses: actions/checkout@v2

    - run: pacman -Tv

    - name: install base-devel
      run: |
        cat pacman.conf >> /etc/pacman.conf
        pacman -Syuq --needed --noconfirm base-devel ccache fd git namcap

    - name: setup makepkg
      run: |
        echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
        echo "PKGDEST=$PWD/pkgs" >> $GITHUB_ENV

        useradd -M builduser && chown -R builduser .
        echo "builduser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builduser
        sed -i -e 's/!ccache/ccache/' /etc/makepkg.conf
        cat makepkg.conf >> /etc/makepkg.conf

    - uses: actions/cache@v1
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ github.sha }}
        restore-keys: |
          ccache-

    - run: sudo -Eu builduser ccache -z

    - run: pacman -Tv

    - name: build packages
      env:
        BUILDDIR: /tmp/makepkg
        PACKAGER: ${{ secrets.PACKAGER }}
      run: |
        for pkg in $(fd -a -t directory); do
          cd "$pkg"
          echo "==> Building $(basename "$pkg")"
          yes | sudo -Eu builduser makepkg -crs --noconfirm
        done

    - name: create repo db
      run: repo-add ${{ env.PKGDEST }}/rsa.db.tar.zst ${{ env.PKGDEST }}/*.pkg.tar.zst
    
    - run: sudo -Eu builduser ccache --show-stats
    - run: cp -LR ${{ env.PKGDEST }} output

    - uses: crazy-max/ghaction-github-pages@v2
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        target_branch: gh-pages
        build_dir: output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
